# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdrink',
            options={'ordering': ['created']},
        ),
    ]
