# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='portion',
            field=models.CharField(choices=[('Pint', 'Pint'), ('Half_pint', 'Half_pint'), ('Bottle', 'Bottle')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('Server', 'Server'), ('Bartender', 'Bartender'), ('Cook', 'Cook'), ('Manager', 'Manager')], default='Server', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='dress',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='food',
            name='finish',
            field=models.CharField(max_length=60),
        ),
    ]
