# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0002_auto_20160710_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='portion',
        ),
    ]
