# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0002_auto_20160708_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
