# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0003_auto_20160708_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quantity', models.IntegerField()),
                ('drink_quantity', models.IntegerField()),
                ('extra_quantity', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco_app.Drink')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco_app.Extra')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco_app.Food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco_app.CustomerOrder')),
            ],
        ),
    ]
