# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0004_orderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='drink_item',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='extra_item',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='notes',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='tag_number',
            field=models.IntegerField(null=True),
        ),
    ]
