# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0004_auto_20160710_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdrink',
            name='placed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='placed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
