# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0005_auto_20160708_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOrder',
            new_name='Customer',
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taco_app.Drink'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='drink_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taco_app.Extra'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='extra_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taco_app.Food'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='food_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
