# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0006_auto_20160708_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(default='drink', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='taco', max_length=20),
        ),
    ]
