# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0007_auto_20160708_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_quantity', models.IntegerField(null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('order_up', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quantity', models.IntegerField(null=True)),
                ('extra_quantity', models.IntegerField(null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('order_up', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.AddField(
            model_name='customer',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(default='add drink', max_length=20),
        ),
        migrations.AlterField(
            model_name='drink',
            name='portion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='preferred_language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(default='add extra', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='add taco', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.AddField(
            model_name='orderfood',
            name='extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taco_app.Extra'),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taco_app.Food'),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='order_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco_app.Customer'),
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taco_app.Drink'),
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='order_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taco_app.Customer'),
        ),
    ]
