# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0008_auto_20160708_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdrink',
            options={'ordering': ['-created', 'order_tag']},
        ),
        migrations.AlterModelOptions(
            name='orderfood',
            options={'ordering': ['-created', 'order_tag']},
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
