# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0009_auto_20160708_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfood',
            options={'ordering': ['created']},
        ),
    ]
