# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0010_auto_20160708_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tag_number',
            field=models.SlugField(null=True),
        ),
    ]
