# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taco_app', '0011_auto_20160708_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taco_app.Extra'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='extra_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taco_app.Food'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='food_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
